---
- hosts: all
  become: yes
  tasks:
  - name: download epl release
    get_url:
      url: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
      dest: /home/ansible/
  - name: install epel
    command: yum install epel-release-latest-7.noarch.rpm
  - name: installing nginx
    yum:
      name: nginx
      state: present
  - name: service enable
    service:
      name: nginx
      state: started
      enabled: yes
