---
- hosts: all
  become: yes
  tasks:
  - name: install epel-relese
    yum:
     name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
     state: present
  - name: install nginx
    yum: 
     name: nginx
     state: present
  - name: service start nginx
    service:
     name: nginx
     state: started
     enabled: yes

